table AMZN_data
	lineageTag: 127dee12-9d94-4001-aff2-20aa01b86dd6

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d41e2dff-aef3-42f3-aaea-0341277494c7
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: int64
		formatString: 0
		lineageTag: c60bd567-bce4-49dc-9d9e-ec39afa9957f
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

	column High
		dataType: int64
		formatString: 0
		lineageTag: 19ccb8fd-0bef-433c-84fb-de0a32d30e21
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

	column Low
		dataType: int64
		formatString: 0
		lineageTag: 07467284-466e-49e1-b5da-12cdef1b25ab
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

	column Close
		dataType: int64
		formatString: 0
		lineageTag: 573ec7ac-8979-4eca-ae8f-73f8b06d1f64
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

	column 'Adj Close'
		dataType: int64
		formatString: 0
		lineageTag: ff899ccc-dc84-48a3-9d68-afb9ed1ac138
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: 460398e9-a9b5-4f08-b056-b0665b489741
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN_data = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\V86368\Berliner Verkehrsbetriebe (BVG) - AöR -\CL_VC-V-Verkehrserträge - Datafreaks\Power BI infos\Version Control\Power-BI-Source-Control-test\AMZN_data.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", Int64.Type}, {"High", Int64.Type}, {"Low", Int64.Type}, {"Close", Int64.Type}, {"Adj Close", Int64.Type}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

